Error404
AustinDidierTran/braceletus pull request #32
Opened 2017-02-28 13:50 UTC by marc1119

Ajout de la page 404.
Ajout de la page pour les détails du patients.
Ajout de la page pour créer/modifier le dossier du patient.
Correction du bug du footer.

2017-02-28 21:59 UTC, benjaminroy requested changes
@marc1119 Je t'ai fait un code review. Tu peux attendre les commentaires de @AustinDidierTran avant de modifier, ou modifier et faire une nouvelle PR après.

2017-02-28 21:59 UTC, benjaminroy commented on app/public/js/appRoutes.js
> +        .when('/patientForm', {
Humm, tu penses pas qu'un modal serait mieux? Si oui, pas besoin d'une nouvelle 'route'. Sinon, laisse faire ce commentaire.

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/error404.html
> +    <h2>404 Not Found</h2>
Ce qui apparaît à l'écran doit être en français !

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/error404.html
> +    <div class="error-actions">
C'est quoi cette classe? Elle ne semble pas exister dans le css.

2017-02-28 21:59 UTC, benjaminroy commented on app/public/stylesheets/app.css
> +  border-radius: 4px;
Est-ce que ces styles sont nécessaires? Le style par défaut des text-area (form-control) de bootstrap ne convient pas??? Qu'est-ce que tu en penses @marc1119 ?

2017-02-28 21:59 UTC, benjaminroy commented on app/public/stylesheets/app.css
> +  border-color: #66afe9;
Même commentaire que le précédent pour ces classes.

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/patient-form.html
> +    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-2 toppad" >
La classe toppad n'existe pas dans ton css...

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/patient-form.html
> +          <h3 class="panel-title"><td></h3>
td ? pourquoi?

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/patient-form.html
> +              <table class="table table-user-information">
La classe table-user-information n'existe pas dans ton CSS on dirait? Quand tu prends un model sur le web, vérifie ce que chaque classe fait, c'est une bonne habitude à prendre :)

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/patient-form.html
> +                    <td><input type="date" class="form-control" value="" placeholder="Date de naissance" ng-model='user.dateNaissance' required></td>
ng-model='user.dateNaissance' : on semble coder en anglais, keep it this way ;) Le même commentaire s'applique partout.

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/patient-form.html
> +                    <td><textarea rows="4" cols="50" placeholder="Alergie(s)" ng-model='user.alergie' required></textarea></td>
Allergie(s) *

2017-02-28 21:59 UTC, benjaminroy commented on app/public/js/appRoutes.js
> +          controller: 'PatientInformationController'
Tu dois créer un nouveau contrôleur pour chaque nouvelle vue. Donc ici un contrôleur: ErrorController. Mais je peux le faire si tu veux, c'est juste pour que tu saches un peu le fonctionnement.

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/error404.html
> +    <img class="img-error" src="\img\error404.png">
C'est quoi la classe img-error? C'est une classe de bootstrap?

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/patient-form.html
> +                    <td><textarea rows="4" cols="50" placeholder="Autre" ng-model='user.autre' required></textarea></td>
Est-ce qu'on veut que la catégorie autre soit vraiment "required" ? Et médicamentations(s) (si le patient ne prend pas de médicaments, par exemple) ?

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/patient-information.html
> +                    <td>{{patient.dateDeNaissance}}</td>
Code en anglais! #uniformité (s'applique partout)

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/patient-information.html
> +    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-2 toppad" >
Encore une fois, qu'est-ce que la classe toppad?

2017-02-28 21:59 UTC, benjaminroy commented on app/public/views/patient-information.html
> +              <table class="table table-user-information">
Encore une fois, qu'est-ce que la classe "table-user-information"

2017-02-28 22:06 UTC, benjaminroy commented on app/public/views/patient-form.html
> +                    <td><textarea rows="4" cols="50" placeholder="Autre" ng-model='user.autre' required></textarea></td>
Aussi, c'est pas les informations d'un utilisateur qu'on affiche, mais bien celles d'un patient.  Dans le code, on utilise "user" pour une infirmière et "patient" pour un patient. Donc ng-model="user.autre" --> ng-model="patient.autre". Aussi, si tu veux voir à quoi ressemble le résultat de ta vue, tu peux hardcoder un objet dans ton contrôleur.

2017-03-01 18:17 UTC, AustinDidierTran commented on app/public/js/appRoutes.js
> +        .when('/patientForm', {
Je crois personnellement que ça mérite d'être une nouvelle view. Par contre, de notre côté, il faudra mettre ça comme page par default si le user n'est pas connecté.

2017-03-01 18:21 UTC, AustinDidierTran commented on app/public/js/appRoutes.js
> +          controller: 'PatientInformationController'
De la façon qu'on marche, je crois pas que c'est nécessaire de lui exiger d'enlever le controller, anyway on va toujours refaire le javascript qu'il va faire, c'est plus pour qu'il puisse travailler sur ses choses.

Mais ouais, si tu veux mieux comprendre, le message à Ben est pertinent.

2017-03-01 18:21 UTC, AustinDidierTran commented on app/public/views/patient-form.html
> +              <a href="" data-original-title="Sauvegarder" data-toggle="tooltip" type="button" class="btn btn-sm btn-success">Sauvegarder <i class="glyphicon glyphicon-edit"></i></a>
J'vais être tannant parce que j'ai un OCD, mais 2 spaces comme indentation, pas 4 😛

2017-03-01 18:23 UTC, benjaminroy commented on app/public/js/appRoutes.js
> +        .when('/patientForm', {
Tu veux que la fenêtre pour ajouter un patient, soit une nouvelle view et la page par défaut? O.o

2017-03-01 18:24 UTC, AustinDidierTran commented on app/public/js/appRoutes.js
> +        .when('/patientForm', {
On parle d'une page d'erreur 404 là, non ?

2017-03-01 18:25 UTC, AustinDidierTran commented on app/public/js/appRoutes.js
> +        .when('/patientForm', {
Ah nevermind...

2017-03-01 18:26 UTC, AustinDidierTran commented on app/public/js/appRoutes.js
> +        .when('/patientForm', {
Mais oui, ça deserve une nouvelle view. À voir le nombre de caractéristiques qu'un patient peu avoir, j'ferais pas ça dans un modal. Ça pourrait être faite dans un modal, mais faudra avoir des sliders pour que ce soit pas pire et en plus, si on est responsive, ça devient chiant à s'assurer que ce soit beau.

2017-03-02 18:45 UTC, AustinDidierTran commented
@marc1119 Wait for @benjaminroy to push his changes, then you'll need to resolve your conflicts so I can merge afterwards

2017-03-06 20:09 UTC, AustinDidierTran commented
@marc1119 Solve conflicts before I can merge

2017-03-19 22:51 UTC, AustinDidierTran commented
@benjaminroy @marc1119 Yo, I didn't merge because conflicts mused be resolved

2017-03-19 22:54 UTC, merged